### ISSUE TITLE
Readme images expired

### ISSUE THREAD

**Issue by adhxtry** [ConAntares/Photonica#1]
Readme images expired. Update them.

**Comment by Photonico** [comment]
Thank you for your notice. I will fix and update this project ASAP(in a month). My computer has some problems, I need to fix them first.

**Comment by Photonico** [comment]
I have fixed some issues including this and updated the themes. 
Please install versions > 1.0.0.
Thanks.

**Comment by adhxtry** [comment]
@Photonico 😅 unfortunately I switched to nvim and I m comfortable with it, but I would really check this one out bcz it was my favourite theme, thanks back.

**Comment by Photonico** [comment]
> 

That's good. I also use both nVim and VSCode, they serve different purposes.
Please tell me what you want to improve or change if you use this theme.
